
[2021-01-28 00:24:44] Traceback (most recent call last):
  File "C:\Users\epics\Documents\Code\MChroma\MChroma\mmwe.py", line 53, in <module>
    jimsloop()
  File "C:\Users\epics\Documents\Code\MChroma\MChroma\mmwe.py", line 51, in jimsloop
    time.sleep(0.01)
NameError: name 'time' is not defined


[2021-01-28 00:27:04] Traceback (most recent call last):
  File "C:\Users\epics\Documents\Code\MChroma\MChroma\mmwe.py", line 63, in <module>
    jimsloop()
  File "C:\Users\epics\Documents\Code\MChroma\MChroma\mmwe.py", line 60, in jimsloop
    window.update()
  File "C:\Users\epics\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1177, in update
    self.tk.call('update')
_tkinter.TclError: can't invoke "update" command: application has been destroyed

